"""change nullable property fields recipe table

Revision ID: 0881e46efbf8
Revises: 880b9055452b
Create Date: 2020-07-26 12:32:50.797674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0881e46efbf8'
down_revision = '880b9055452b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=3000),
               nullable=False)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('recipes', 'description',
               existing_type=sa.VARCHAR(length=3000),
               nullable=True)
    op.alter_column('recipes', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
