"""add indexes for tables

Revision ID: 0a1b3edac304
Revises: 73c7592c9255
Create Date: 2020-07-31 01:18:54.556621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1b3edac304'
down_revision = '73c7592c9255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_index(op.f('ix_recipes_type'), 'recipes', ['type'], unique=False)
    op.drop_index('ix_recipes_created', table_name='recipes')
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.create_index('ix_recipes_created', 'recipes', ['created'], unique=False)
    op.drop_index(op.f('ix_recipes_type'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    # ### end Alembic commands ###
