"""add foreng key recept to recipe step table

Revision ID: 0d863528ba84
Revises: 9f1d55aa8076
Create Date: 2020-07-26 13:07:09.406704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d863528ba84'
down_revision = '9f1d55aa8076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_steps', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_steps', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_steps', type_='foreignkey')
    op.drop_column('recipe_steps', 'recipe_id')
    # ### end Alembic commands ###
