"""add likes and selected_recipes tables

Revision ID: 0f49b04c0eb0
Revises: b6fe00ae098d
Create Date: 2020-07-29 23:56:48.112254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f49b04c0eb0'
down_revision = 'b6fe00ae098d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selected_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('recipe_x_tag', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipe_x_tag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_x_tag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipe_x_tag', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('selected_recipes')
    op.drop_table('likes')
    # ### end Alembic commands ###
