"""remove required image_id for recipes table

Revision ID: 395907e3a93e
Revises: 70d45ddbfc78
Create Date: 2020-07-28 23:37:08.212404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395907e3a93e'
down_revision = '70d45ddbfc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
