"""add image to recipe

Revision ID: 70d45ddbfc78
Revises: fecd478ca681
Create Date: 2020-07-27 23:00:36.459837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d45ddbfc78'
down_revision = 'fecd478ca681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_id', sa.Integer(), nullable=False))
    op.alter_column('recipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'recipes', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.alter_column('recipes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recipes', 'image_id')
    # ### end Alembic commands ###
