"""add count_likes for recipe table

Revision ID: 73c7592c9255
Revises: 402cbbe662f9
Create Date: 2020-07-30 00:25:03.915678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c7592c9255'
down_revision = '402cbbe662f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('count_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'count_likes')
    # ### end Alembic commands ###
