"""add field count_recipe for user table

Revision ID: b6fe00ae098d
Revises: 395907e3a93e
Create Date: 2020-07-29 01:08:03.321073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fe00ae098d'
down_revision = '395907e3a93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('count_recipe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'count_recipe')
    # ### end Alembic commands ###
